---
yandex_cloud_services:
  - service: managed-postgresql
    serviceId: c9qtttoh7uptlmbb53ia
    folderId: b1g3ht3298osdcvd027i
    bearer_token: ${YANDEX_BEARER_TOKEN}
    scrape_interval: 60s
  - service: managed-mongodb
    serviceId: c9qgd65n5j0mrjmiht9r
    folderId: b1g3ht3298osdcvd027i
    bearer_token: ${YANDEX_BEARER_TOKEN}
    scrape_interval: 60s
