stages:
  - build
  - test
  - release
  - package-chart
  - deploy
  - notify

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  JAVA_OPTS: -XX:MaxRAMPercentage=90

cache:
  paths:
    - frontend/dist

build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/sausage-frontend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true
  only:
    changes:
      - frontend/**/*

sonarqube-frontend-sast:
  stage: test
  needs: ["build-frontend"]
  script:
    - cd frontend
    - npm install -g sonarqube-scanner
    - >
      sonar-scanner
      -Dsonar.projectKey=$SONAR_PROJECT_KEY_FRONT
      -Dsonar.projectName=${SONAR_PROJECT_NAME}FRONTEND
      -Dsonar.sources=.
      -Dsonar.host.url=$SONARQUBE_URL
      -Dsonar.login=$SONAR_LOGIN
  allow_failure: true
  only:
    changes:
      - frontend/**/*

gitlab-sast:
  stage: test
  needs: ["build-frontend"]
  trigger:
    include:
      - template: Security/SAST.gitlab-ci.yml
  only:
    changes:
      - frontend/**/*

release-frontend:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA $VERSION
  needs: ["build-frontend"]
  only:
    changes:
      - frontend/**/*

package-and-upload-frontend:
  stage: package-chart
  image: alpine/helm:latest
  needs: ["release-frontend"]
  before_script:
    - apk add --no-cache curl gettext yq
  script:
    - |
      CHART_DIR="sausage-store-chart"
      
      # Обновляем версии в сабчарте frontend
      yq eval ".version = \"$VERSION\"" -i ${CHART_DIR}/charts/frontend/Chart.yaml
      yq eval ".appVersion = \"$VERSION\"" -i ${CHART_DIR}/charts/frontend/Chart.yaml
      
      # Переходим в директорию сабчарта frontend
      cd ${CHART_DIR}/charts/frontend
      
      # Пакетируем сабчарт frontend отдельно
      helm package . -d ../../../ --version $VERSION
      
      # Возвращаемся в корневую директорию
      cd ../../../
      
      # Проверяем что файл создался
      ls -la *.tgz
      echo "Frontend chart packaged: frontend-${VERSION}.tgz"
      
      # Загружаем frontend chart в Nexus
      echo "Uploading frontend chart to Nexus..."
      curl -v -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} \
        ${HELM_REPO_URL} \
        --upload-file frontend-${VERSION}.tgz

      echo "Frontend chart uploaded successfully!"
  artifacts:
    paths:
      - frontend-${VERSION}.tgz
    expire_in: 1 week
  only:
    changes:
      - sausage-store-chart/charts/frontend/**/*
      - frontend/**/*


deploy-frontend:
  stage: deploy
  image: alpine/helm:latest
  environment:
    name: production/frontend
  when: manual
  needs: ["package-and-upload-frontend"]
  before_script:
    - apk add --no-cache gettext
    - mkdir -p ~/.kube/
    - echo "$KUBECONFIG" > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - |
      kubectl create secret docker-registry docker-config-secret \
        --docker-server=$CI_REGISTRY \
        --docker-username=$CI_REGISTRY_USER \
        --docker-password=$CI_REGISTRY_PASSWORD \
        --namespace=std-ext-010-34 \
        --dry-run=client -o yaml | kubectl apply -f -
    - helm repo add nexus ${HELM_REPO_URL} --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS}
    - helm repo update
  script:
    - echo "Available frontend chart versions:"
    - helm search repo nexus/frontend --versions | head -10

    - helm upgrade --install sausage-frontend nexus/frontend \
        --version $VERSION \
        --namespace std-ext-010-34 \
        --create-namespace \
        --wait \
        --timeout 5m

    - helm list -n std-ext-010-34
    - kubectl get pods -n std-ext-010-34 -l app.kubernetes.io/name=frontend
    - kubectl get ingress -n std-ext-010-34
  after_script:
    - rm -f ~/.kube/config
  only:
    changes:
      - sausage-store-chart/charts/frontend/**/*
      - frontend/**/*

telegram-notification-frontend:
  stage: notify
  needs: ["deploy-frontend"]
  script:
    - |
      MESSAGE="✅ std-ext-010-34 задеплоил frontend версии $VERSION через Helm

      📦 Frontend образ: ${CI_REGISTRY_IMAGE}/sausage-frontend:$VERSION
      📦 Backend образ: ${CI_REGISTRY_IMAGE}/sausage-backend:$VERSION
      📊 Chart: nexus/sausage-store:$VERSION
      🚀 Pipeline: $CI_PIPELINE_URL
      🎯 Namespace: std-ext-010-34
    - |
      curl -X POST -H "Content-type: application/json" \
        --data "{\"chat_id\": \"$CHAT_ID\", \"text\": \"$MESSAGE\"}" \
        https://api.telegram.org/bot$BOT_TOKEN/sendMessage
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/