version: "3.8"

services:
  backend-blue:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:${VERSION}
    env_file:
      - .env
    healthcheck:
      test: wget -q -O /dev/null http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6 
    restart: always
    networks:
      - sausage-store

  backend-green:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:${VERSION}
    env_file:
      - .env
    healthcheck:
      test: wget -q -O /dev/null http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6 
    restart: always
    networks:
      - sausage-store

  backend-report:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend-report:${VERSION}
    container_name: sausage-store-backend-report
    restart: always
    env_file:
      - .env
    networks:
      - sausage-store

  frontend:
    image: ${CI_REGISTRY_IMAGE}/sausage-frontend:${VERSION}
    container_name: sausage-store-frontend
    env_file:
      - .env
    restart: always
    ports:
      - "80:80"
    networks:
      - sausage-store
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  sausage-store: