---
apiVersion: v2
type: application
name: sausage-store
description: Sausage Store Helm Chart

version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: backend-report
    version: 0.1.0
    repository: "file://charts/backend-report"