global:
  namespace: std-ext-010-34

backend:
  enabled: true
  image:
    repository: ""
  secrets:
    springDatasourceUrl: ""
    postgresUser: ""
    postgresPassword: ""
    mongoUser: ""
    mongoPassword: ""
    mongoHost: ""
    mongoDbName: ""

frontend:
  enabled: true
  image:
    repository: ""
  ingress:
    host: "alimov-iskander-34.k8s.praktikum-services.tech"

backend-report:
  enabled: true
  image:
    repository: ""
  mongo:
    user: ""
    password: ""
    host: ""
    dbname: ""
  env:
    DB: ""

imagePullSecrets:
  - name: docker-config-secret