---
replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: docker-config-secret

nameOverride: ""
fullnameOverride: ""

environment: production

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30081

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 20%

revisionHistoryLimit: 12

secrets:
  springDatasourceUrl: ""
  postgresUser: ""
  postgresPassword: ""
  mongoUser: ""
  mongoPassword: ""
  mongoHost: ""
  mongoDbName: ""

vpa:
  enabled: true
  updateMode: "Off"
  minAllowed:
    cpu: 50m
    memory: 64Mi
  maxAllowed:
    cpu: 1000m
    memory: 1Gi