---
replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: docker-config-secret

nameOverride: ""
fullnameOverride: ""

environment: production

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
  hosts:
    - host: alimov-iskander-34.k8s.praktikum-services.tech
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-tls
      hosts:
        - alimov-iskander-34.k8s.praktikum-services.tech

certificate:
  enabled: false 
  secretName: frontend-tls
  issuerName: letsencrypt-prod
  issuerKind: Issuer
  dnsNames:
    - alimov-iskander-34.k8s.praktikum-services.tech

issuer:
  enabled: false  
  name: letsencrypt-prod
  email: your-email@example.com
  server: https://acme-v02.api.letsencrypt.org/directory

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

revisionHistoryLimit: 12

nginxConfig:
  defaultConf: |
    server {
      listen 80;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://backend:8080;
      }
    }
