---
replicaCount: 2

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: docker-config-secret

nameOverride: ""
fullnameOverride: ""

environment: production

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30082

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

revisionHistoryLimit: 12

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - backend-report
          topologyKey: kubernetes.io/hostname

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

env:
  port: "8080"
  db: ""

mongo:
  user: ""
  password: ""
  host: ""
  dbname: ""
  port: "27018"