# Default values for backend-report
image:
  repository: "" # Будет передано из CI/CD
  pullPolicy: IfNotPresent

replicas: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Настройки сервиса
service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30082

# Настройки HPA
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 75

# Переменные окружения
env:
  PORT: "8080"
  DB: ""

# MongoDB connection
mongo:
  user: ""
  password: ""
  host: ""
  dbname: ""

# Docker registry secret
imagePullSecrets:
  - name: docker-config-secret