---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ index .Values "backend-report" "image" "tag" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.global.environment }}"
spec:
  replicas: {{ index .Values "backend-report" "replicaCount" }}
  revisionHistoryLimit: {{ index .Values "backend-report" "revisionHistoryLimit" }}
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-report
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-report
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/version: "{{ index .Values "backend-report" "image" "tag" }}"
        app.kubernetes.io/component: backend-report
        app.kubernetes.io/part-of: sausage-store
        env: "{{ .Values.global.environment }}"
    spec:
      {{- with (index .Values "backend-report" "affinity") }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend-report
          image: "{{ index .Values "backend-report" "image" "repository" }}:{{ index .Values "backend-report" "image" "tag" }}"
          imagePullPolicy: {{ index .Values "backend-report" "image" "pullPolicy" }}
          env:
            - name: VERSION
              value: "{{ index .Values "backend-report" "image" "tag" }}"
            - name: PORT
              value: {{ index .Values "backend-report" "env" "port" | quote }}
            - name: REPORTS_MONGODB_URI
              value: "mongodb://{{ index .Values "backend-report" "mongo" "user" }}:{{ index .Values "backend-report" "mongo" "password" }}@{{ index .Values "backend-report" "mongo" "host" }}:{{ index .Values "backend-report" "mongo" "port" }}/{{ index .Values "backend-report" "mongo" "dbname" }}?tls=true&tlsInsecure=true"
            - name: DB
              value: {{ index .Values "backend-report" "env" "db" | quote }}
          ports:
            - name: http
              containerPort: {{ index .Values "backend-report" "service" "targetPort" }}
              protocol: TCP
          resources:
            {{- toYaml (index .Values "backend-report" "resources") | nindent 12 }}
      {{- with .Values.global.registry.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}