apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-report.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 12
  selector:
    matchLabels:
      {{- include "backend-report.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-report.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ include "backend-report.name" . }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: backend-report
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "VERSION"
              value: "{{ .Chart.AppVersion }}"
            - name: "PORT"
              value: {{ .Values.env.PORT | quote }}
            - name: "DB"
              value: {{ .Values.env.DB | quote }}
            - name: "REPORTS_MONGODB_URI"
              value: "mongodb://{{ .Values.mongo.user }}:{{ .Values.mongo.password }}@{{ .Values.mongo.host }}:27018/{{ .Values.mongo.dbname }}?tls=true&tlsInsecure=true"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}