---
apiVersion: v1
kind: Service
metadata:
  name: backend-report
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ index .Values "backend-report" "image" "tag" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
spec:
  type: {{ index .Values "backend-report" "service" "type" }}
  ports:
    - port: {{ index .Values "backend-report" "service" "port" }}
      targetPort: {{ index .Values "backend-report" "service" "targetPort" }}
      {{- if and (eq (index .Values "backend-report" "service" "type") "NodePort") (index .Values "backend-report" "service" "nodePort") }}
      nodePort: {{ index .Values "backend-report" "service" "nodePort" }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"