apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-tls
  namespace: std-ext-010-34
spec:
  secretName: frontend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - alimov-iskander-34.k8s.praktikum-services.tech
