{{- if .Values.backend.vpa.enabled }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend-vpa-{{ .Release.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Values.backend.image.tag }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sausage-store
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  updatePolicy:
    updateMode: {{ .Values.backend.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: backend
        controlledResources:
          - cpu
          - memory
        minAllowed:
          cpu: {{ .Values.backend.vpa.minAllowed.cpu }}
          memory: {{ .Values.backend.vpa.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.backend.vpa.maxAllowed.cpu }}
          memory: {{ .Values.backend.vpa.maxAllowed.memory }}
{{- end }}