groups:
  - name: Sausage store rules
    rules:
    - alert: InstanceDown
      expr: up{app="backend"} == 0
      for: 1m
      labels:
        severity: critical
        project: "sausage_store"
        component: "Backend"
    - alert: Http500Errors
      expr: increase(http_server_requests_seconds_count{status="500"}[5m]) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Обнаружены HTTP 500 ошибки"
        description: "На сервисе за последние 5 минут появились запросы с кодом 500."
    - alert: SlowOrdersP95
      expr: |
        histogram_quantile(
          0.95,
          sum(rate(http_server_requests_seconds_bucket{method="POST",uri="/api/orders",outcome="SUCCESS"}[5m])) by (le)
        ) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Медленные POST /api/orders (p95 > 100ms)"
        description: "95 перцентиль времени выполнения POST /api/orders превышает 100 мс в течение 5 минут."
    - alert: PrometheusActuatorErrors
      expr: increase(http_server_requests_seconds_count{uri="/actuator/prometheus",outcome!="SUCCESS"}[2m]) > 0
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: "Ошибки при /actuator/prometheus"
        description: "За последние 2 минуты обнаружены запросы с ошибками на /actuator/prometheus."
